-- MySQL Script generated by MySQL Workbench
-- Wed Dec 19 10:31:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TennisRus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TennisRus` ;

-- -----------------------------------------------------
-- Schema TennisRus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TennisRus` DEFAULT CHARACTER SET utf8 ;
USE `TennisRus` ;

-- -----------------------------------------------------
-- Table `TennisRus`.`spelers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TennisRus`.`spelers` ;

CREATE TABLE IF NOT EXISTS `TennisRus`.`spelers` (
  `spelersnr` INT NOT NULL,
  `naam` VARCHAR(25) NOT NULL,
  `voorletter` VARCHAR(3) NOT NULL,
  `voorvoegsel` VARCHAR(5) NOT NULL,
  `geb_jaar` SMALLINT NOT NULL,
  `geslacht` CHAR NOT NULL,
  `jaartoe` SMALLINT NOT NULL,
  `woonplaats` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`spelersnr`),
  UNIQUE INDEX `Spelersnr_UNIQUE` (`spelersnr` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TennisRus`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TennisRus`.`teams` ;

CREATE TABLE IF NOT EXISTS `TennisRus`.`teams` (
  `teamnr` INT NOT NULL,
  `spelersnr` INT NOT NULL,
  `divisie` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`teamnr`),
  UNIQUE INDEX `Teamnr_UNIQUE` (`teamnr` ASC),
  INDEX `fk_teams_spelers1_idx` (`spelersnr` ASC),
  CONSTRAINT `fk_teams_spelers1`
    FOREIGN KEY (`spelersnr`)
    REFERENCES `TennisRus`.`spelers` (`spelersnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TennisRus`.`wedstrijden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TennisRus`.`wedstrijden` ;

CREATE TABLE IF NOT EXISTS `TennisRus`.`wedstrijden` (
  `wedstrijdnr` INT NOT NULL,
  `teamnr` INT NOT NULL,
  `spelersnr` INT NOT NULL,
  `gewonnen` VARCHAR(45) NOT NULL,
  `verloren` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`wedstrijdnr`),
  UNIQUE INDEX `wedstrijdnr_UNIQUE` (`wedstrijdnr` ASC),
  INDEX `fk_wedstrijden_spelers1_idx` (`spelersnr` ASC),
  INDEX `fk_wedstrijden_teams1_idx` (`teamnr` ASC),
  CONSTRAINT `fk_wedstrijden_spelers1`
    FOREIGN KEY (`spelersnr`)
    REFERENCES `TennisRus`.`spelers` (`spelersnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wedstrijden_teams1`
    FOREIGN KEY (`teamnr`)
    REFERENCES `TennisRus`.`teams` (`teamnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TennisRus`.`boetes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TennisRus`.`boetes` ;

CREATE TABLE IF NOT EXISTS `TennisRus`.`boetes` (
  `betalingsnr` INT NOT NULL,
  `spelersnr` INT NOT NULL,
  `datum` DATE NOT NULL,
  `bedrag` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`betalingsnr`),
  UNIQUE INDEX `betalingsnr_UNIQUE` (`betalingsnr` ASC),
  INDEX `fk_boetes_spelers1_idx` (`spelersnr` ASC),
  CONSTRAINT `fk_boetes_spelers1`
    FOREIGN KEY (`spelersnr`)
    REFERENCES `TennisRus`.`spelers` (`spelersnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
